// language-config.js
export const translations = {
    en: {
        enterSearch: 'Enter search query',
        toggleTheme: 'Toggle Theme',
        settings: 'Settings',
        reportBug: 'Report Bug',
        suggestFeature: 'Suggest Feature',
        addSite: 'Add Site',
        language: 'Language',
        reportABug: 'Report a Bug',
        suggestAFeature: 'Suggest a Feature',
        addASite: 'Add a Site',
        promoteYourSite: 'Promote Your Site',
        submit: 'Submit',
        submitted: 'Submitted!',
        describeBug: 'Describe the bug...',
        yourSuggestion: 'Your suggestion...',
        siteUrl: 'http://',
        promoteMessage: 'Enter your site details for paid inclusion...',
        generalSettings: 'General Settings',
        mostVisitedSitesFirst: 'Most visited sites first',
        resetVisitedSites: 'Reset visited sites',
        showLogoOnMouseOver: 'Show logo on mouse over',
        openResultsInNewTab: 'Open results in new tab',
        rows: 'Rows',
        sites: 'Sites',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Maps',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'General',
        ai: 'AI',
        buy: 'Buy',
        social: 'Social',
        forum: 'Forum',
        cookieText: 'We use cookies to improve your experience.',
        learnMore: 'Learn more',
        accept: 'Accept',
        decline: 'Decline'
    },
    es: {
        enterSearch: 'Ingrese consulta de búsqueda',
        toggleTheme: 'Cambiar tema',
        settings: 'Configuración',
        reportBug: 'Reportar error',
        suggestFeature: 'Sugerir función',
        addSite: 'Agregar sitio',
        language: 'Idioma',
        reportABug: 'Reportar un Error',
        suggestAFeature: 'Sugerir una Función',
        addASite: 'Agregar un Sitio',
        promoteYourSite: 'Promocionar tu Sitio',
        submit: 'Enviar',
        submitted: '¡Enviado!',
        describeBug: 'Describe el error...',
        yourSuggestion: 'Tu sugerencia...',
        siteUrl: 'http://',
        promoteMessage: 'Ingresa los detalles de tu sitio para inclusión pagada...',
        generalSettings: 'Configuración General',
        mostVisitedSitesFirst: 'Sitios más visitados primero',
        resetVisitedSites: 'Restablecer sitios visitados',
        showLogoOnMouseOver: 'Mostrar logo al pasar el ratón',
        openResultsInNewTab: 'Abrir resultados en nueva pestaña',
        rows: 'Filas',
        sites: 'Sitios',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Mapas',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'General',
        ai: 'IA',
        buy: 'Comprar',
        social: 'Social',
        forum: 'Foro',
        cookieText: 'Usamos cookies para mejorar tu experiencia.',
        learnMore: 'Aprende más',
        accept: 'Aceptar',
        decline: 'Rechazar'
    },
    hi: {
        enterSearch: 'खोज क्वेरी दर्ज करें',
        toggleTheme: 'थीम टॉगल करें',
        settings: 'सेटिंग्स',
        reportBug: 'बग रिपोर्ट करें',
        suggestFeature: 'सुविधा सुझाएं',
        addSite: 'साइट जोड़ें',
        language: 'भाषा',
        reportABug: 'बग रिपोर्ट करें',
        suggestAFeature: 'एक सुविधा सुझाएं',
        addASite: 'एक साइट जोड़ें',
        promoteYourSite: 'अपनी साइट को बढ़ावा दें',
        submit: 'जमा करें',
        submitted: 'जमा किया गया!',
        describeBug: 'बग का वर्णन करें...',
        yourSuggestion: 'आपका सुझाव...',
        siteUrl: 'http://',
        promoteMessage: 'भुगतान शामिल करने के लिए अपनी साइट का विवरण दर्ज करें...',
        generalSettings: 'सामान्य सेटिंग्स',
        mostVisitedSitesFirst: 'सबसे अधिक देखे गए साइट्स पहले',
        resetVisitedSites: 'देखे गए साइट्स रीसेट करें',
        showLogoOnMouseOver: 'माउस ओवर पर लोगो दिखाएं',
        openResultsInNewTab: 'नए टैब में परिणाम खोलें',
        rows: 'पंक्तियाँ',
        sites: 'साइट्स',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'नक्शे',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'सामान्य',
        ai: 'AI',
        buy: 'खरीदें',
        social: 'सामाजिक',
        forum: 'मंच',
        cookieText: 'हम आपका अनुभव बेहतर करने के लिए कुकीज़ का उपयोग करते हैं।',
        learnMore: 'और जानें',
        accept: 'स्वीकार करें',
        decline: 'अस्वीकार करें'
    },
    bn: {
        enterSearch: 'অনুসন্ধান প্রশ্ন লিখুন',
        toggleTheme: 'থিম টগল করুন',
        settings: 'সেটিংস',
        reportBug: 'বাগ রিপোর্ট করুন',
        suggestFeature: 'বৈশিষ্ট্য প্রস্তাব করুন',
        addSite: 'সাইট যোগ করুন',
        language: 'ভাষা',
        reportABug: 'একটি বাগ রিপোর্ট করুন',
        suggestAFeature: 'একটি বৈশিষ্ট্য প্রস্তাব করুন',
        addASite: 'একটি সাইট যোগ করুন',
        promoteYourSite: 'আপনার সাইট প্রচার করুন',
        submit: 'জমা দিন',
        submitted: 'জমা দেওয়া হয়েছে!',
        describeBug: 'বাগ বর্ণনা করুন...',
        yourSuggestion: 'আপনার প্রস্তাব...',
        siteUrl: 'http://',
        promoteMessage: 'প্রদত্ত অন্তর্ভুক্তির জন্য আপনার সাইটের বিবরণ লিখুন...',
        generalSettings: 'সাধারণ সেটিংস',
        mostVisitedSitesFirst: 'সবচেয়ে বেশি পরিদর্শিত সাইটগুলি প্রথমে',
        resetVisitedSites: 'পরিদর্শিত সাইট রিসেট করুন',
        showLogoOnMouseOver: 'মাউস ওভারে লোগো দেখান',
        openResultsInNewTab: 'নতুন ট্যাবে ফলাফল খুলুন',
        rows: 'সারি',
        sites: 'সাইট',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'মানচিত্র',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'সাধারণ',
        ai: 'AI',
        buy: 'কিনুন',
        social: 'সামাজিক',
        forum: 'ফোরাম',
        cookieText: 'আমরা আপনার অভিজ্ঞতা উন্নত করতে কুকিজ ব্যবহার করি।',
        learnMore: 'আরও জানুন',
        accept: 'গ্রহণ করুন',
        decline: 'প্রত্যাখ্যান করুন'
    },
    ar: {
        enterSearch: 'أدخل استعلام البحث',
        toggleTheme: 'تبديل الثيم',
        settings: 'الإعدادات',
        reportBug: 'الإبلاغ عن خطأ',
        suggestFeature: 'اقتراح ميزة',
        addSite: 'إضافة موقع',
        language: 'اللغة',
        reportABug: 'الإبلاغ عن خطأ',
        suggestAFeature: 'اقتراح ميزة',
        addASite: 'إضافة موقع',
        promoteYourSite: 'الترويج لموقعك',
        submit: 'إرسال',
        submitted: 'تم الإرسال!',
        describeBug: 'صف الخطأ...',
        yourSuggestion: 'اقتراحك...',
        siteUrl: 'http://',
        promoteMessage: 'أدخل تفاصيل موقعك للإدراج المدفوع...',
        generalSettings: 'الإعدادات العامة',
        mostVisitedSitesFirst: 'المواقع الأكثر زيارة أولاً',
        resetVisitedSites: 'إعادة تعيين المواقع التي تمت زيارتها',
        showLogoOnMouseOver: 'إظهار الشعار عند تمرير الفأرة',
        openResultsInNewTab: 'فتح النتائج في علامة تبويب جديدة',
        rows: 'الصفوف',
        sites: 'المواقع',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'خرائط',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'عام',
        ai: 'AI',
        buy: 'شراء',
        social: 'اجتماعي',
        forum: 'منتدى',
        cookieText: 'نستخدم ملفات تعريف الارتباط لتحسين تجربتك.',
        learnMore: 'تعرف على المزيد',
        accept: 'قبول',
        decline: 'رفض'
    },
    fr: {
        enterSearch: 'Entrez une requête de recherche',
        toggleTheme: 'Changer de thème',
        settings: 'Paramètres',
        reportBug: 'Signaler un bug',
        suggestFeature: 'Suggérer une fonctionnalité',
        addSite: 'Ajouter un site',
        language: 'Langue',
        reportABug: 'Signaler un Bug',
        suggestAFeature: 'Suggérer une Fonctionnalité',
        addASite: 'Ajouter un Site',
        promoteYourSite: 'Promouvoir Votre Site',
        submit: 'Soumettre',
        submitted: 'Soumis!',
        describeBug: 'Décrivez le bug...',
        yourSuggestion: 'Votre suggestion...',
        siteUrl: 'http://',
        promoteMessage: 'Entrez les détails de votre site pour une inclusion payante...',
        generalSettings: 'Paramètres Généraux',
        mostVisitedSitesFirst: 'Sites les plus visités en premier',
        resetVisitedSites: 'Réinitialiser les sites visités',
        showLogoOnMouseOver: 'Afficher le logo au survol',
        openResultsInNewTab: 'Ouvrir les résultats dans un nouvel onglet',
        rows: 'Lignes',
        sites: 'Sites',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Cartes',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'Général',
        ai: 'IA',
        buy: 'Acheter',
        social: 'Social',
        forum: 'Forum',
        cookieText: 'Nous utilisons des cookies pour améliorer votre expérience.',
        learnMore: 'En savoir plus',
        accept: 'Accepter',
        decline: 'Refuser'
    },
    pt: {
        enterSearch: 'Digite a consulta de pesquisa',
        toggleTheme: 'Alternar tema',
        settings: 'Configurações',
        reportBug: 'Reportar bug',
        suggestFeature: 'Sugerir recurso',
        addSite: 'Adicionar site',
        language: 'Idioma',
        reportABug: 'Reportar um Bug',
        suggestAFeature: 'Sugerir um Recurso',
        addASite: 'Adicionar um Site',
        promoteYourSite: 'Promover Seu Site',
        submit: 'Enviar',
        submitted: 'Enviado!',
        describeBug: 'Descreva o bug...',
        yourSuggestion: 'Sua sugestão...',
        siteUrl: 'http://',
        promoteMessage: 'Digite os detalhes do seu site para inclusão paga...',
        generalSettings: 'Configurações Gerais',
        mostVisitedSitesFirst: 'Sites mais visitados primeiro',
        resetVisitedSites: 'Redefinir sites visitados',
        showLogoOnMouseOver: 'Mostrar logotipo ao passar o mouse',
        openResultsInNewTab: 'Abrir resultados em nova aba',
        rows: 'Linhas',
        sites: 'Sites',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Mapas',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'Geral',
        ai: 'IA',
        buy: 'Comprar',
        social: 'Social',
        forum: 'Fórum',
        cookieText: 'Usamos cookies para melhorar sua experiência.',
        learnMore: 'Saiba mais',
        accept: 'Aceitar',
        decline: 'Recusar'
    },
    ru: {
        enterSearch: 'Введите поисковый запрос',
        toggleTheme: 'Переключить тему',
        settings: 'Настройки',
        reportBug: 'Сообщить об ошибке',
        suggestFeature: 'Предложить функцию',
        addSite: 'Добавить сайт',
        language: 'Язык',
        reportABug: 'Сообщить об Ошибке',
        suggestAFeature: 'Предложить Функцию',
        addASite: 'Добавить Сайт',
        promoteYourSite: 'Продвигать Ваш Сайт',
        submit: 'Отправить',
        submitted: 'Отправлено!',
        describeBug: 'Опишите ошибку...',
        yourSuggestion: 'Ваше предложение...',
        siteUrl: 'http://',
        promoteMessage: 'Введите данные вашего сайта для платного включения...',
        generalSettings: 'Общие Настройки',
        mostVisitedSitesFirst: 'Наиболее посещаемые сайты первыми',
        resetVisitedSites: 'Сбросить посещенные сайты',
        showLogoOnMouseOver: 'Показывать логотип при наведении',
        openResultsInNewTab: 'Открывать результаты в новой вкладке',
        rows: 'Строки',
        sites: 'Сайты',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Карты',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'Общие',
        ai: 'ИИ',
        buy: 'Купить',
        social: 'Социальные',
        forum: 'Форум',
        cookieText: 'Мы используем куки для улучшения вашего опыта.',
        learnMore: 'Узнать больше',
        accept: 'Принять',
        decline: 'Отклонить'
    },
    id: {
        enterSearch: 'Masukkan kueri pencarian',
        toggleTheme: 'Ganti tema',
        settings: 'Pengaturan',
        reportBug: 'Laporkan bug',
        suggestFeature: 'Sarankan fitur',
        addSite: 'Tambah situs',
        language: 'Bahasa',
        reportABug: 'Laporkan Bug',
        suggestAFeature: 'Sarankan Fitur',
        addASite: 'Tambah Situs',
        promoteYourSite: 'Promosikan Situs Anda',
        submit: 'Kirim',
        submitted: 'Terkirim!',
        describeBug: 'Jelaskan bug...',
        yourSuggestion: 'Saran Anda...',
        siteUrl: 'http://',
        promoteMessage: 'Masukkan detail situs Anda untuk penyertaan berbayar...',
        generalSettings: 'Pengaturan Umum',
        mostVisitedSitesFirst: 'Situs paling sering dikunjungi dulu',
        resetVisitedSites: 'Reset situs yang dikunjungi',
        showLogoOnMouseOver: 'Tampilkan logo saat mouse di atas',
        openResultsInNewTab: 'Buka hasil di tab baru',
        rows: 'Baris',
        sites: 'Situs',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Peta',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'Umum',
        ai: 'AI',
        buy: 'Beli',
        social: 'Sosial',
        forum: 'Forum',
        cookieText: 'Kami menggunakan cookie untuk meningkatkan pengalaman Anda.',
        learnMore: 'Pelajari lebih lanjut',
        accept: 'Terima',
        decline: 'Tolak'
    },
    it: {
        enterSearch: 'Inserisci query di ricerca',
        toggleTheme: 'Cambia tema',
        settings: 'Impostazioni',
        reportBug: 'Segnala bug',
        suggestFeature: 'Suggerisci funzionalità',
        addSite: 'Aggiungi sito',
        language: 'Lingua',
        reportABug: 'Segnala un Bug',
        suggestAFeature: 'Suggerisci una Funzionalità',
        addASite: 'Aggiungi un Sito',
        promoteYourSite: 'Promuovi il Tuo Sito',
        submit: 'Invia',
        submitted: 'Inviato!',
        describeBug: 'Descrivi il bug...',
        yourSuggestion: 'Il tuo suggerimento...',
        siteUrl: 'http://',
        promoteMessage: 'Inserisci i dettagli del tuo sito per l’inclusione a pagamento...',
        generalSettings: 'Impostazioni Generali',
        mostVisitedSitesFirst: 'Siti più visitati per primi',
        resetVisitedSites: 'Ripristina siti visitati',
        showLogoOnMouseOver: 'Mostra logo al passaggio del mouse',
        openResultsInNewTab: 'Apri risultati in una nuova scheda',
        rows: 'Righe',
        sites: 'Siti',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Mappe',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'Generale',
        ai: 'AI',
        buy: 'Compra',
        social: 'Sociale',
        forum: 'Forum',
        cookieText: 'Utilizziamo i cookie per migliorare la tua esperienza.',
        learnMore: 'Scopri di più',
        accept: 'Accetta',
        decline: 'Rifiuta'
    },
    de: {
        enterSearch: 'Suchanfrage eingeben',
        toggleTheme: 'Thema wechseln',
        settings: 'Einstellungen',
        reportBug: 'Fehler melden',
        suggestFeature: 'Funktion vorschlagen',
        addSite: 'Seite hinzufügen',
        language: 'Sprache',
        reportABug: 'Einen Fehler Melden',
        suggestAFeature: 'Eine Funktion Vorschlagen',
        addASite: 'Eine Seite Hinzufügen',
        promoteYourSite: 'Ihre Seite Bewerben',
        submit: 'Absenden',
        submitted: 'Gesendet!',
        describeBug: 'Beschreiben Sie den Fehler...',
        yourSuggestion: 'Ihr Vorschlag...',
        siteUrl: 'http://',
        promoteMessage: 'Geben Sie die Details Ihrer Seite für eine kostenpflichtige Aufnahme ein...',
        generalSettings: 'Allgemeine Einstellungen',
        mostVisitedSitesFirst: 'Meistbesuchte Seiten zuerst',
        resetVisitedSites: 'Besuchte Seiten zurücksetzen',
        showLogoOnMouseOver: 'Logo bei Mauszeiger anzeigen',
        openResultsInNewTab: 'Ergebnisse in neuem Tab öffnen',
        rows: 'Reihen',
        sites: 'Seiten',
        google: 'Google',
        youtube: 'YouTube',
        wikipedia: 'Wikipedia',
        spotify: 'Spotify',
        netflix: 'Netflix',
        maps: 'Karten',
        chatgpt: 'ChatGPT',
        grok: 'Grok',
        gemini: 'Gemini',
        copilot: 'Copilot',
        claude: 'Claude',
        perplexity: 'Perplexity',
        amazon: 'Amazon',
        ebay: 'eBay',
        alibaba: 'Alibaba',
        walmart: 'Walmart',
        mercadolibre: 'MercadoLibre',
        etsy: 'Etsy',
        x: 'X',
        facebook: 'Facebook',
        tiktok: 'TikTok',
        twitch: 'Twitch',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
        reddit: 'Reddit',
        stackoverflow: 'Stack Overflow',
        discord: 'Discord',
        '4chan': '4chan',
        quora: 'Quora',
        ted: 'TED',
        general: 'Allgemein',
        ai: 'KI',
        buy: 'Kaufen',
        social: 'Sozial',
        forum: 'Forum',
        cookieText: 'Wir verwenden Cookies, um Ihre Erfahrung zu verbessern.',
        learnMore: 'Erfahren Sie mehr',
        accept: 'Akzeptieren',
        decline: 'Ablehnen'
    }
};

export const languageFlags = {
    en: '🇬🇧',
    es: '🇪🇸',
    hi: '🇮🇳',
    bn: '🇧🇩',
    ar: '🇸🇦',
    fr: '🇫🇷',
    pt: '🇵🇹',
    ru: '🇷🇺',
    id: '🇮🇩',
    it: '🇮🇹',
    de: '🇩🇪'
};